version: '3'
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - development.env
    volumes:
      - .:/shopify_marketplace_api

volumes:
  postgres: