version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
         environment:
          RAILS_ENV: test
          RACK_ENV: test
          REDIS_URL: "redis://localhost:6379"
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: rails_test_user
       - image: redis
       - image: circleci/postgres:9.4
         environment:
          POSTGRES_USER: rails_test_user
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: shopify_marketplace_api_test

    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: Get dependencies
          command: sudo apt-get update;

      - restore_cache:
          keys:
            - shopify_marketplace_api-bundle-v2-{{ checksum "Gemfile.lock" }}
            - shopify_marketplace_api-bundle-v2-

      - run:
          name: Bundle install
          command: bundle check || bundle install

      - save_cache:
          key: shopify_marketplace_api-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Wait for redis
          command: |
            dockerize -wait tcp://localhost:6379 -timeout 1m

      - run:
          name: Rails test
          command: bundle exec rake test

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          prefix: tests