version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
         environment:
          RAILS_ENV: test
          RACK_ENV: test
          REDIS_URL: "redis://localhost:6379"
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: rails_test_user
       - image: redis
       - image: circleci/postgres:9.4
         environment:
          POSTGRES_USER: rails_test_user
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: shopify_marketplace_api_test

    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: Get dependencies
          command: sudo apt-get update; sudo apt-get install

      - restore_cache:
          keys:
            - shopify_marketplace_api-bundle-v2-{{ checksum "Gemfile.lock" }}
            - shopify_marketplace_api-bundle-v2-

      - run:
          name: Bundle install
          command: bundle check || bundle install

      - save_cache:
          key: shopify_marketplace_api-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Rails test
          command: bundle exec rake test

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          prefix: tests

  deploy:
    docker:
      - image: circleci/python

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install AWS
          command: |
            sudo pip install awscli
            aws --version

      - run:
          name: Login AWS
          command: eval $(aws ecr get-login --no-include-email --region $AWS_REGION)

      - run:
          name: Build and push Docker image
          command: |
            docker build -t $ECR_ENDPOINT/shopify_marketplace_api:$CIRCLE_SHA1 .
            docker push $ECR_ENDPOINT/shopify_marketplace_api:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master   